package com.gathering.android.event

const val KEY_ARGUMENT_SELECTED_IMAGE = "KEY_ARGUMENT_SELECTED_IMAGE"
const val KEY_ARGUMENT_SELECTED_ADDRESS = "KEY_ARGUMENT_SELECTED_ADDRESS"
const val KEY_ARGUMENT_SELECTED_ATTENDEE_LIST = "KEY_ARGUMENT_SELECTED_ATTENDEE_LIST"
const val KEY_ARGUMENT_UPDATE_MY_EVENT_LIST = "KEY_ARGUMENT_UPDATE_MY_EVENT_LIST"
const val KEY_ARGUMENT_UPDATE_USER_INFO_DATA = "KEY_ARGUMENT_UPDATE_USER_INFO_DATA"

